/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_shirun_jnitest33_TestJni */

#ifndef _Included_com_shirun_jnitest33_TestJni
#define _Included_com_shirun_jnitest33_TestJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_shirun_jnitest33_TestJni
 * Method:    getJniString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_shirun_jnitest33_TestJni_getJniString
  (JNIEnv *, jobject,jstring);

#ifdef __cplusplus
}
#endif
#endif
